server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 10240
  port: 8091
  servlet:
    context-path: /channel
logging:
  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=${spring.cloud.nacos.config.group}&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-config.xml