batch:
  callback-service-host: https://li-ptdev.insuremo.com
  disabled: true
cfg:
  provider:
    mo:
      url: http://172.25.10.218
data:
  provider:
    mo:
      url: http://172.25.10.218
datasource:
  trans:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/salesbs-config?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    liquibase:
      change-log: classpath:/db/upgrade-db.xml
      enabled: true
    password: 123456
    username: root
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
hazelcast:
  kubernetes:
    enable: false
  password: local
limobs:
  adapter:
    provider:
      pa: PolicyAdminProviderImpl_Mock
  es:
    hosts: http://172.25.13.87:9200
opentracing:
  jaeger:
    udp-sender:
      host: 172.25.16.153
      port: 30091
pa:
  provider:
    mo:
      url: http://172.25.10.218
pd:
  url: http://172.25.10.218
spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/salesbs-config?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: 123456
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ejb:
          interceptor: com.ebao.li.framework.entity.AuditDataInterceptor
    show-sql: true
  redis:
    host: 172.25.16.24
    password: eAf012m@31
    port: 6379
springfox:
  documentation:
    swagger:
      v2:
        host: localhost:8090
        scheme: http